name: AdchainSDK
options:
  minimumXcodeGenVersion: 2.33.0
  deploymentTarget:
    iOS: 14.0
  
targets:
  AdchainSDK:
    type: framework
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: AdchainSDK/Sources
        excludes:
          - "**/*.md"
          - "**/Tests"
    headers:
      public:
        - AdchainSDK/AdchainSDK.h
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.oneself.adchainsdk
        PRODUCT_NAME: AdchainSDK
        INFOPLIST_FILE: AdchainSDK/Info.plist
        BUILD_LIBRARY_FOR_DISTRIBUTION: YES
        DEFINES_MODULE: YES
        SKIP_INSTALL: NO
        SWIFT_VERSION: 5.5
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        ENABLE_BITCODE: NO
        IPHONEOS_DEPLOYMENT_TARGET: 14.0
        TARGETED_DEVICE_FAMILY: "1,2"
        VALID_ARCHS: "arm64 x86_64"
        ONLY_ACTIVE_ARCH: NO
    dependencies:
      - sdk: UIKit.framework
      - sdk: Foundation.framework
      - sdk: WebKit.framework
      - sdk: AdSupport.framework
      - sdk: AppTrackingTransparency.framework
    scheme:
      buildTargets:
        - AdchainSDK